# Generated by Django 4.2.7 on 2024-02-20 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=256, unique=True)),
                ("title", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="SpecializationType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256)),
                (
                    "specialization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="job.specialization"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256)),
                ("price_from", models.IntegerField(blank=True, null=True)),
                ("price_to", models.IntegerField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="job.company")),
                ("experience", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="job.experience")),
                ("region", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="job.region")),
                (
                    "specialization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="job.specialization"),
                ),
            ],
        ),
    ]
