# Generated by Django 4.2.7 on 2024-02-20 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="region",
        ),
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="jobs", to="job.company"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="experience",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="jobs", to="job.experience"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="specialization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="jobs", to="job.specialization"
            ),
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="districts", to="job.region"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="district",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="jobs", to="job.district"
            ),
            preserve_default=False,
        ),
    ]
