# Generated by Django 4.2.7 on 2024-02-20 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_remove_job_region_alter_job_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="specialization",
        ),
        migrations.AddField(
            model_name="job",
            name="specialization_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="job.specializationtype",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="specializationtype",
            name="specialization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specializationtypes",
                to="job.specialization",
            ),
        ),
    ]
