# Generated by Django 4.2.7 on 2024-02-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0003_remove_job_specialization_job_specialization_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
