# Generated by Django 4.2.7 on 2024-02-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0004_company_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
