# Generated by Django 4.2.7 on 2024-02-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0005_job_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(null=True, upload_to="logos/"),
        ),
    ]
