# Generated by Django 4.2.7 on 2024-02-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0007_job_is_top"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="published_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
