# Generated by Django 4.2.7 on 2024-02-21 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0008_job_published_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmploymentType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256)),
                ("code", models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="employment_type",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="job.employmenttype"),
        ),
    ]
