# Generated by Django 4.2.7 on 2024-02-21 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0009_employmenttype_job_employment_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyBranch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name="district",
            name="neighboring_cities",
            field=models.ManyToManyField(blank=True, to="job.district"),
        ),
        migrations.AlterField(
            model_name="job",
            name="employment_type",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="jobs", to="job.employmenttype"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="branch",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="job.companybranch"),
        ),
    ]
