# Generated by Django 4.2.7 on 2024-02-21 07:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0010_companybranch_district_neighboring_cities_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256)),
                ("code", models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="district",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="job.district"),
        ),
        migrations.AddField(
            model_name="company",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="additional_info",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="work_schedule",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="job.workschedule"),
        ),
    ]
