# Generated by Django 4.2.7 on 2024-02-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0011_workschedule_company_district_company_is_verified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=225)),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="required_skills",
            field=models.ManyToManyField(blank=True, to="job.skill"),
        ),
    ]
